// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoginProvider } from "@/context/LoginContext";
import { CartProvider } from "@/context/ItemsInCart";
import CartSidebar from "@/components/cart/cartSidebar";
import fetchProfileUser from "@/utils/fetchProfileUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EXCLUSIVE",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const head = await fetchProfileUser()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoginProvider>
          <CartProvider>
          <CartSidebar check={head.user} />
            {children}
          </CartProvider>
        </LoginProvider>
      </body>
    </html>
  );
}
